// <auto-generated />
namespace odeToFood.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RestaurantAndRestaurantReviewTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestaurantAndRestaurantReviewTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201904151925089_RestaurantAndRestaurantReviewTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
